### ISSUE TITLE
 IOTA Wallet generates different addresses than us

### ISSUE THREAD

**Issue by Emiller88** [IOTA-Ledger/blue-app-iota#2]
See: [Address-test](https://github.com/IOTA-Ledger/blue-app-iota/tree/address-test) for tests.

@peterwilli :

> I now narrowed it down to trits_to_words which seems to be returning different results too
> it's called by Kerl so it might be the problem
> I edited the word_to_trits function, but both my version and the original give different results than IOTA.lib.js
> so there's room for improvement there
> @diskings let me know when back, you can read up on this :stuck_out_tongue:
> tl;dr: seems like trints_to_words is giving flawed results, in turn polluting kerl
> IOTA word conversion: word conversion Uint32Array [
>   1067197689,
>   3486346416,
>   3826045239,
>   11191935,
>   2408969240,
>   4013166582,
>   2021906185,
>   2062403453,
>   980365332,
>   1369509650,
>   2280778051,
>   2689248909 ]
> Ledger [original conversion.c] Response: 244606070 587111619 3262320401 took: 0 seconds (first 3 numbers)
> Ledger [edited conversion.c] Response: 2377009824 587111619 3262320401 took: 0 seconds

**Comment by peterwilli** [comment]
We're currently in the process of tracking it down. This morning I found out our output starts to differ at the tryte to word conversion function (and in turn pollutes Kerl output) so that's what we're focusing on right now.

**Comment by Wollac** [comment]
Address generation has been fixed with d06bd60560ccb689d444b21a76d43ea7617df9c5
