### ISSUE TITLE
Should Nano S Documentation contain recovery phrase entropy mention?

### ISSUE THREAD

**Issue by kjetilkjeka** [IOTA-Ledger/blue-app-iota#20]
I understand that a 24 word BIP39 recovery phrase represent less information than the 27 tryte iota seed. Personally I'm very interested in how this problem has been handled but didn't find any mention of it anywhere. Perhaps it should be added to the file `Ledger Nano S Documentation.md`

If i recall correctly there was some talk of squeezing the passphrase for the remaining entropy. If this was the chosen solution, should it be added as a security concern that no passphrase will be less secure than a strong passphrase even if no one obtains access to your recovery key?

**Comment by Wollac** [comment]
You are absolutely correct, the 24 word mnemonics only provide 256 bit of entropy, while an IOTA seed is 384 bit converted. That is why an additional function is used to convert this mnemonic seed and an optional passphrase (not your pin number) of your choosing into a 512 bit binary seed. This happens according to the BIP39 standard on the Ledger Nano using system calls. As there is no direct support for Kerl here, the extended child key (512 bit) of a corresponding BIP32 path is then hashed (using Kerl) to derive the final 243 trit seed.
Thus, to use the full entropy supported by IOTA an additional sufficiently long passphrase is needed! On the other hand, there are other factors that might have a higher security impact, like choosing proper random mnemonics (the Ledger Nano uses a TRNG for that matter) or selecting a higher security level...

Thanks for this remark! Although having (only) 256 bits of entropy does not pose a security problem, it does not support the full potential of the IOTA seed. We'll add a remark to our documentation the next time we revise it.

**Comment by muXxer** [comment]
I added that information here:
https://github.com/IOTA-Ledger/blue-app-iota#recovery-phrase-entropy
